Application/urls.py
from django.urls import path, include
from . import views
app_name = 'Application'

urlpatterns = [

    path('', views.allViews, name = 'all-views'),
    path('department/add/', views.DepartmentCreateView.as_view(), name = 'department-add'),
    path('department/<str:pk>/', views.DepartmentDetailView.as_view(), name = 'department-detail'),
    path('department/', views.DepartmentAllView, name = 'department'),
    path('student/add/', views.StudentCreateView.as_view(), name = 'student-add'),
    path('student/<str:pk>/', views.StudentDetailView.as_view(), name = 'student-detail'),
    path('student/',views.StudentAllView, name = 'student'),
    path('accounts/', include('django.contrib.auth.urls'), name = 'accounts'),
    path('course/add/', views.CourseCreateView.as_view(), name='course-add'),
    path('course/<str:pk>/', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/', views.CourseAllView, name='course'),

]

University/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Application.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Application/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime
from django.shortcuts import render
from django.urls import reverse
from django.conf.urls import include, url
from django.conf import settings
from django.core.files.storage import FileSystemStorage

class Department(models.Model):
    dept_name = models.CharField(max_length=200, primary_key=True)
    building = models.CharField(max_length=200)
    budget = models.CharField(max_length=200)
    def get(self):
        return self.clean()
    def get_absolute_url(self):
        return reverse('Application:department-detail', kwargs={'pk': self.pk})
    
class Course(models.Model):
    course_id = models.CharField(unique=True, max_length=200)
    title = models.CharField(max_length=200)
    dept_name = models.ForeignKey(Department, on_delete=models.CASCADE)
    credits = models.IntegerField()
    def get(self):
        return self.clean()
    def get_absolute_url(self):
        return reverse('Application:course-detail', kwargs={'pk': self.pk})
    
class Student(models.Model):
    ID = models.CharField(max_length=200, primary_key=True)
    firstName = models.CharField(max_length=200)
    lastName = models.CharField(max_length=200)
    dept_name = models.ForeignKey(Department, on_delete=models.CASCADE)
    tot_cred = models.IntegerField()
    stud_img = models.ImageField(upload_to='media/')
    def get(self):
        return self.clean()
    def get_absolute_url(self):
        return reverse('Application:student-detail', kwargs={'pk': self.pk})

Application/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views.generic import CreateView, View, DetailView, TemplateView
from .models import Department, Student, Course
from django import forms

class StudentCreateView(CreateView):
    model = Student
    fields = ('ID', 'firstName', 'lastName', 'dept_name', 'tot_cred', 'stud_img')

class StudentDetailView(DetailView):
    model = Student
    
def StudentAllView(request):
    students = Student.objects.all()
    return render(request, 'Application/student_all_view.html', {'students': students})
    
class DepartmentCreateView(CreateView):
    model = Department
    fields = ('dept_name', 'building', 'budget')

class DepartmentDetailView(DetailView):
    model = Department

def DepartmentAllView(request):
    departments = Department.objects.all()
    return render(request, 'Application/department_all_view.html', {'departments': departments})

class CourseCreateView(CreateView):
    model = Course
    fields = ('course_id', 'title', 'dept_name', 'credits')

class CourseDetailView(DetailView):
    model = Course

def CourseAllView(request):
    courses = Course.objects.all()
    return render(request, 'Application/course_all_view.html', {'courses': courses})

def allViews(request):
    # students = Student.objects.all()
    return render(request, 'Application/all-views.html', {})

def IndexView(request):
    return render(request, 'static/index.html', {'name': 'ROHIT_CHOUGULE'})

Application/templates/Application/all-views.html
{% extends 'Application/base.html' %}
{% block title %} WALCHAND COLLEGE OF ENGINEERING SANGLI {% endblock %}
{% block title1 %} WALCHAND COLLEGE OF ENGINEERING {% endblock %}

{% block content %}

<br>
        <img src="https://static.careers360.mobi/media/presets/720X480/colleges/social-media/media-gallery/2600/2018/5/24/Walchand-College-of-Engineering-Sangli2.jpg">
        <br>
        <br>
        <a href = "{% url 'Application:student' %}">Student Data</a> <br>
        <a href = "{% url 'Application:department' %}">Department Data</a><br>
        <a href = "{% url 'Application:course' %}">Course Data</a><br>

<br>

<a href="{%url 'Application:all-views' %}" ><b>UNIVERSITY HOME</b></a>
{% endblock %}

Application/templates/Application/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>{% block title%} {% endblock %}</title>
</head>
<body>
    <center>

        <div class="jumbotron">

            <div class="row justify-content-center">
                <div class="col-8">
                    {% if user.is_authenticated %}
                        Currently Logged in as : {{ user.username }}
                        <h1 class="mt-2">{% block title1 %} {% endblock %}</h1>
                        <hr class="mt-0 mb-4">
                        {% block content %}
                        {% endblock %}
                    <br>
                    <br><a href="{% url 'Application:logout' %}"><b>SignOff</b></a>
                    {% else %}
                        <p>Walchand College of Engineering Sangli</p>
                        <img src="https://static.careers360.mobi/media/presets/720X480/colleges/social-media/media-gallery/2600/2018/5/24/Walchand-College-of-Engineering-Sangli2.jpg">
                        <br><br>
                        <p>Please Sign-in for further actions</p>
                        <br>
                        <b><a href="{% url 'Application:login' %}">LOGIN</a></b>

                    {% endif %}

                </div>
            </div>
        </div>
    </center>
</body>
</html>

Application/templates/Application/course_all_view.html
{% extends 'Application/base.html' %}

{% load crispy_forms_tags %}
{% block title %} All Courses {% endblock %}
{% block title1 %} All Courses {% endblock %}
{% block content %}

<img src="https://image.shutterstock.com/image-illustration/business-services-technical-help-gear-260nw-794147113.jpg"><br><br><br>

<ol>
{% for course in courses %}
    <li>
        Course ID: <a href="{% url 'Application:course'%}{{course.pk}}/">{{course.course_id}}</a>
        <br>
    </li> <br>
{% endfor %}
</ol>

<br>
<a href = "{% url 'Application:course-add' %}">Add Course</a> <br> <br>
<a href= "{%url 'Application:all-views' %}"> HOME PAGE</a>
{% endblock %}

Application/templates/Application/course_detail.html
{% extends 'Application/base.html' %}
{% block title %} Course Details {% endblock %}
{% block title1 %} Course Details {% endblock %}

{% block content %}
<b>Course ID: </b> {{course.course_id}}
<br>
<b>Title: </b> <p>{{course.title}}</p>
<br>
<b>Department: </b> <a href="{% url 'Application:department'%}{{course.dept_name.pk}}/">{{course.dept_name.pk}}</a>
<br>
<b>Total Credits: </b> {{course.credits}}
<br>
<a href= "{%url 'Application:all-views' %}">UNIVERSITY HOME</a>
{% endblock %}

Application/templates/Application/course_form.html
{% extends 'Application/base.html' %}

{% load crispy_forms_tags %}
{% block title %} Add New Course {% endblock %}
{% block title1 %} Add New Course {% endblock %}
{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy}}
    <button type = 'submit' class = 'btn btn-success'> Submit</button>
</form>
<br><br><a href= "{%url 'Application:all-views' %}">UNIVERSITY HOME</a>
{% endblock %}

Application/templates/Application/department_all_view.html
{% extends 'Application/base.html' %}

{% load crispy_forms_tags %}
{% block title %} All Departments {% endblock %}
{% block title1 %} All Departments {% endblock %}
{% block content %}
<img src="https://image.shutterstock.com/image-illustration/business-services-technical-help-gear-260nw-794147113.jpg">
<br> <br><br>

<ol>
{% for department in departments %}
    <li>
        Department Name: <a href="{% url 'Application:department'%}{{department.pk}}/">{{department.dept_name}}</a>
        <br>
    </li> <br>
{% endfor %}
</ol>
<a href = "{% url 'Application:department-add' %}">Add departments</a>
<br><br><a href= "{%url 'Application:all-views' %}">UNIVERSITY HOME</a>
{% endblock %}

Application/templates/Application/department_detail.html
{% extends 'Application/base.html' %}
{% block title %} Department Details {% endblock %}
{% block title1 %} Department Details {% endblock %}

{% block content %}

<b>Name: </b> <p>{{department.dept_name}}</p> <br>
<b>Building: </b> <p>{{department.building}}</p> <br>
<b>Budget: </b> <p>{{department.budget}}</p> <br>
<br><br><a href= "{%url 'Application:all-views' %}">UNIVERSITY HOME</a>

{% endblock %}

Application/templates/Application/department_form.html
{% extends 'Application/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Add New Department {% endblock %}

<h3>{% block title1 %} Add New Department {% endblock %}</h3>

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    {{ form|crispy}}
    <button type = 'submit' class = 'btn btn-success'> Submit</button>
</form>
<br><br><a href= "{%url 'Application:all-views' %}">UNIVERSITY HOME</a>
{% endblock %}

Application/templates/Application/student_detail.html
{% extends 'Application/base.html' %}
{% block title %} Student Details {% endblock %}
{% block title1 %} Student Details {% endblock %}

{% block content %}

<img src = '{{student.stud_img.url}}' width="20%" height="40%" alt="Img Not Found" align="center"> <br>
<br><br>
<b>Name: {{student.firstName}} {{student.lastName}}
<br><br>
<b>Department: </b> <a href="{% url 'Application:department'%}{{student.dept_name.pk}}/">{{student.dept_name.pk}}</a>
<br>
<br>
    <a href= "{%url 'Application:all-views' %}">UNIVERSITY HOME</a>
{% endblock %}

Application/templates/Application/student_form.html
{% extends 'Application/base.html' %}

{% load crispy_forms_tags %}
{% block title %} Add New Student {% endblock %}
{% block title1 %} Add New Student {% endblock %}
{% block content %}

<form action="" method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy}}
    <button type = 'submit' class = 'btn btn-success'> Submit</button>
</form>
<br><br><a href="{%url 'Application:all-views' %}" ><b>UNIVERSITY HOME</b></a>
{% endblock %}